const DEFAULT_ERROR_CODE = 500;
const NOT_FOUND_ERROR_CODE = 404;
const INVALID_PARAMS_ERROR_CODE = 400;

module.exports = {
  DEFAULT_ERROR_CODE,
  NOT_FOUND_ERROR_CODE,
  INVALID_PARAMS_ERROR_CODE,
};
